const test = {
  id: "tt0118480",
  title: "Stargate SG-1",
  originalTitle: "",
  fullTitle: "Stargate SG-1 (TV Series 1997–2007)",
  type: "TVSeries",
  year: "1997",
  image:
    "https://m.media-amazon.com/images/M/MV5BMTc3MjEwMTc5N15BMl5BanBnXkFtZTcwNzQ2NjQ4NA@@._V1_Ratio0.6762_AL_.jpg",
  releaseDate: "1997-07-27",
  plot: "A secret military team, SG-1, is formed to explore other planets through the recently discovered Stargates.",
  awards: "Nominated for 9 Primetime Emmys, 18 wins & 97 nominations total",
  stars: "Richard Dean Anderson, Michael Shanks, Amanda Tapping",
  starList: [
    { id: "nm0000760", name: "Richard Dean Anderson" },
    { id: "nm0788218", name: "Michael Shanks" },
    { id: "nm0850102", name: "Amanda Tapping" },
  ],
  tvSeriesInfo: {
    yearEnd: "2007",
    creators: "Jonathan Glassner, Brad Wright",
    creatorList: [
      { id: "nm0322106", name: "Jonathan Glassner" },
      { id: "nm0942249", name: "Brad Wright" },
    ],
  },
  genres: "Action, Adventure, Drama",
  genreList: [
    { key: "Action", value: "Action" },
    { key: "Adventure", value: "Adventure" },
    { key: "Drama", value: "Drama" },
  ],
  companies:
    "Double Secret Productions, Gekko Film Corp., Kawoosh! Productions IX",
  companyList: [
    { id: "co0129774", name: "Double Secret Productions" },
    { id: "co0005244", name: "Gekko Film Corp." },
    { id: "co0214390", name: "Kawoosh! Productions IX" },
  ],
  countries: "USA, Canada",
  countryList: [
    { key: "USA", value: "USA" },
    { key: "Canada", value: "Canada" },
  ],
  languages: "English",
  languageList: [{ key: "English", value: "English" }],
  contentRating: "TV-14",
  imDbRating: "8.4",
  imDbRatingVotes: "93757",
  metacriticRating: "48",
  ratings: {
    imDbId: "tt0118480",
    title: "Stargate SG-1",
    fullTitle: "Stargate SG-1 (TV Series 1997–2007)",
    type: "TVSeries",
    year: "1997",
    imDb: "8.4",
    metacritic: "48",
    theMovieDb: "8.3",
    rottenTomatoes: "88",
    filmAffinity: "6.6",
    errorMessage: "",
  },
  imdbID: "tt0118480",
  tmdbID: "4629",
  imdbRating: 84,
  imdbVoteCount: 93812,
  tmdbRating: 82,
  backdropPath: "/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
  backdropURLs: {
    1280: "https://image.tmdb.org/t/p/w1280/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
    300: "https://image.tmdb.org/t/p/w300/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
    780: "https://image.tmdb.org/t/p/w780/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
    original:
      "https://image.tmdb.org/t/p/original/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
  },
  originalTitle: "Stargate SG-1",
  genres: [28, 12],
  countries: ["CA", "US"],
  year: 1997,
  firstAirYear: 1997,
  lastAirYear: 2007,
  episodeRuntimes: [42, 60, 43, 45],
  cast: [
    "Gary Jones",
    "Richard Dean Anderson",
    "Amanda Tapping",
    "Christopher Judge",
    "Tony Amendola",
    "Michael Shanks",
    "Don S. Davis",
  ],
  significants: ["Brad Wright", "Jonathan Glassner"],
  title: "Stargate SG-1",
  overview:
    "The story of Stargate SG-1 begins about a year after the events of the feature film, when the United States government learns that an ancient alien device called the Stargate can access a network of such devices on a multitude of planets. SG-1 is an elite Air Force special operations team, one of more than two dozen teams from Earth who explore the galaxy and defend against alien threats such as the Goa'uld, Replicators, and the Ori.",
  video: "wSRS7c_UqaM",
  posterPath: "/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
  posterURLs: {
    154: "https://image.tmdb.org/t/p/w154/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
    185: "https://image.tmdb.org/t/p/w185/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
    342: "https://image.tmdb.org/t/p/w342/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
    500: "https://image.tmdb.org/t/p/w500/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
    780: "https://image.tmdb.org/t/p/w780/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
    92: "https://image.tmdb.org/t/p/w92/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
    original:
      "https://image.tmdb.org/t/p/original/9Jegw0yle4x8jlmLNZon37Os27h.jpg",
  },
  seasons: 10,
  episodes: 214,
  age: -1,
  status: 4,
  tagline: "Saving the world… one episode at a time",
  streamingInfo: {
    netflix: {
      us: {
        link: "https://www.netflix.com/title/70155599/",
        added: 1607039010,
        leaving: 1669957199,
      },
    },
    prime: {
      us: {
        link: "https://www.amazon.com/gp/video/detail/0OBBM0NR5YWKZ4K5G07YPTP8C5/",
        added: 1662777193,
        leaving: 0,
      },
    },
  },
  originalLanguage: "en",
};

export { test };
