[
  {
    source_id: 391,
    name: "Pluto TV",
    type: "free",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://pluto.tv/on-demand/series/stargate-sg-1-ptv1/season/1/episode/children-of-the-gods-part-1-1997-1-1-ptv1?utm_medium=deeplink&",
    format: "HD",
    price: null,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 349,
    name: "iTunes",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://tv.apple.com/us/episode/children-of-the-gods/umc.cmc.1qywqchlvmiwx0wnuybse1qjr?playableId=tvs.sbd.9001%3A1342460154&showId=umc.cmc.10dkkj9ftj6k72vr4i76ogknm",
    format: "SD",
    price: 1.99,
    seasons: 10,
    episodes: 214,
  },
  {
    source_id: 349,
    name: "iTunes",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://tv.apple.com/us/episode/children-of-the-gods/umc.cmc.1qywqchlvmiwx0wnuybse1qjr?playableId=tvs.sbd.9001%3A1342460154&showId=umc.cmc.10dkkj9ftj6k72vr4i76ogknm",
    format: "HD",
    price: 2.99,
    seasons: 10,
    episodes: 214,
  },
  {
    source_id: 140,
    name: "Google Play",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://play.google.com/store/tv/show?amp=&cdid=tvseason-miKszvRS2ViYLMRbaEzBjA&gl=us&hl=en&id=GqNOkSPPK-Y",
    format: "SD",
    price: 1.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 140,
    name: "Google Play",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://play.google.com/store/tv/show?amp=&cdid=tvseason-miKszvRS2ViYLMRbaEzBjA&gl=us&hl=en&id=GqNOkSPPK-Y",
    format: "HD",
    price: 2.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 307,
    name: "VUDU",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://www.vudu.com/content/movies/details/Stargate-SG-1-Children-of-the-Gods/427290",
    format: "SD",
    price: 1.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 307,
    name: "VUDU",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://www.vudu.com/content/movies/details/Stargate-SG-1-Children-of-the-Gods/427290",
    format: "HD",
    price: 2.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 344,
    name: "YouTube",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url: "https://www.youtube.com/watch?v=NhQsOWWszpk",
    format: "HD",
    price: 2.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 344,
    name: "YouTube",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url: "https://www.youtube.com/watch?v=NhQsOWWszpk",
    format: "SD",
    price: 1.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 398,
    name: "Microsoft Store",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url: "https://www.microsoft.com/en-us/p/season-1/8d6kgwzlcx6z",
    format: "SD",
    price: 1.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 398,
    name: "Microsoft Store",
    type: "buy",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url: "https://www.microsoft.com/en-us/p/season-1/8d6kgwzlcx6z",
    format: "HD",
    price: 2.99,
    seasons: 10,
    episodes: 213,
  },
  {
    source_id: 26,
    name: "Amazon Prime",
    type: "sub",
    region: "US",
    ios_url: "Deeplinks available for paid plans only.",
    android_url: "Deeplinks available for paid plans only.",
    web_url:
      "https://watch.amazon.com/detail?gti=amzn1.dv.gti.02b38d28-cbe6-dd60-267c-0439e49fc961",
    format: "HD",
    price: null,
    seasons: 10,
    episodes: 213,
  },
];
